"""Add actual_print_duration_s to Job model

Revision ID: 05bd6e4a333d
Revises: e2e3dead7215
Create Date: 2025-09-14 23:13:31.206778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05bd6e4a333d'
down_revision = 'e2e3dead7215'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('actual_print_duration_s', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('actual_print_duration_s')
        batch_op.drop_column('completed_at')

    # ### end Alembic commands ###
