"""Add cost fields to job model

Revision ID: 2f2565d62144
Revises: a073be7bbb07
Create Date: 2025-09-16 19:57:35.799153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f2565d62144'
down_revision = 'a073be7bbb07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preparation_time_min', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('post_processing_time_min', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('employee_hourly_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('material_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('machine_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('personnel_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_cost', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('total_cost')
        batch_op.drop_column('personnel_cost')
        batch_op.drop_column('machine_cost')
        batch_op.drop_column('material_cost')
        batch_op.drop_column('employee_hourly_rate')
        batch_op.drop_column('post_processing_time_min')
        batch_op.drop_column('preparation_time_min')

    # ### end Alembic commands ###
