"""Add LayoutItem model for digital twin

Revision ID: 415fd023d95b
Revises: 2f2565d62144
Create Date: 2025-09-19 15:08:42.087735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '415fd023d95b'
down_revision = '2f2565d62144'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('layout_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('item_type', sa.Enum('PRINTER', 'TABLE', 'SHELF', 'OBJECT', name='layoutitemtype'), nullable=False),
    sa.Column('model_path', sa.String(length=255), nullable=False),
    sa.Column('position_x', sa.Float(), nullable=True),
    sa.Column('position_y', sa.Float(), nullable=True),
    sa.Column('position_z', sa.Float(), nullable=True),
    sa.Column('rotation_y', sa.Float(), nullable=True),
    sa.Column('scale', sa.Float(), nullable=True),
    sa.Column('printer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['printer_id'], ['printer.id'], name=op.f('fk_layout_item_printer_id_printer')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_layout_item'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('layout_item')
    # ### end Alembic commands ###
