"""Add source_stl_filename to Job model

Revision ID: 62ab1705a15a
Revises: 8babb5a0a783
Create Date: 2025-09-24 18:09:03.926362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62ab1705a15a'
down_revision = '8babb5a0a783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_stl_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('source_stl_filename')

    # ### end Alembic commands ###
