"""Add full rotation and visibility to LayoutItem

Revision ID: 81fcd5f5d89c
Revises: 415fd023d95b
Create Date: 2025-09-20 02:30:01.274616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81fcd5f5d89c'
down_revision = '415fd023d95b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('layout_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_visible', sa.Boolean(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('layout_item', schema=None) as batch_op:
        batch_op.drop_column('is_visible')

    # ### end Alembic commands ###
