"""Add dimensions_z_mm

Revision ID: 880b690ec9fd
Revises: 109e98d87010
Create Date: 2025-10-14 20:50:49.181420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '880b690ec9fd'
down_revision = '109e98d87010'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('g_code_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dimensions_z_mm', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('g_code_file', schema=None) as batch_op:
        batch_op.drop_column('dimensions_z_mm')

    # ### end Alembic commands ###
