"""Rename printer stats columns to historical base values

Revision ID: 9897bd9645b1
Revises: 62ab1705a15a
Create Date: 2025-09-28 22:48:52.898075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9897bd9645b1'
down_revision = '62ab1705a15a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('printer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('historical_print_hours', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('historical_filament_used_g', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('historical_jobs_count', sa.Integer(), nullable=True))
        batch_op.drop_column('total_filament_used_g')
        batch_op.drop_column('total_print_hours')
        batch_op.drop_column('total_jobs_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('printer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_jobs_count', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('total_print_hours', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('total_filament_used_g', sa.FLOAT(), nullable=True))
        batch_op.drop_column('historical_jobs_count')
        batch_op.drop_column('historical_filament_used_g')
        batch_op.drop_column('historical_print_hours')

    # ### end Alembic commands ###
