"""Add color to LayoutItem

Revision ID: 990b52749fee
Revises: 81fcd5f5d89c
Create Date: 2025-09-20 12:43:32.028159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '990b52749fee'
down_revision = '81fcd5f5d89c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('layout_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scale_x', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('scale_y', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('scale_z', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('color', sa.String(length=7), nullable=True))
        batch_op.drop_column('scale')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('layout_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scale', sa.FLOAT(), nullable=True))
        batch_op.drop_column('color')
        batch_op.drop_column('scale_z')
        batch_op.drop_column('scale_y')
        batch_op.drop_column('scale_x')

    # ### end Alembic commands ###
