"""Add filament drying fields to Spool

Revision ID: a073be7bbb07
Revises: 05bd6e4a333d
Create Date: 2025-09-15 18:20:01.543110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a073be7bbb07' # Behalten Sie Ihre neue Revisions-ID bei
down_revision = '05bd6e4a333d' # Passen Sie dies an die vorherige Revision an
branch_labels = None
depends_on = None


def upgrade():
    # ### Korrigierte Befehle ###
    with op.batch_alter_table('filament_spool', schema=None) as batch_op:
        # Schritt 1: Spalte als nullable erstellen
        batch_op.add_column(sa.Column('is_drying', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('drying_start_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('drying_temp', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('drying_humidity', sa.Integer(), nullable=True))

    # Schritt 2: Bestehende Zeilen mit dem Standardwert füllen
    op.execute('UPDATE filament_spool SET is_drying = 0 WHERE is_drying IS NULL')

    # Schritt 3: Spalte auf NOT NULL setzen
    with op.batch_alter_table('filament_spool', schema=None) as batch_op:
        batch_op.alter_column('is_drying', existing_type=sa.Boolean(), nullable=False)
    # ### Ende der Korrektur ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filament_spool', schema=None) as batch_op:
        batch_op.drop_column('drying_humidity')
        batch_op.drop_column('drying_temp')
        batch_op.drop_column('drying_start_time')
        batch_op.drop_column('is_drying')
    # ### end Alembic commands ###