"""Add maintenance system

Revision ID: e0f98318ecdb
Revises: f953499bc20c
Create Date: 2025-10-07 21:06:07.539449

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'e0f98318ecdb'
down_revision = 'f953499bc20c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_consumable')
    with op.batch_alter_table('consumable', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consumable', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    op.create_table('_alembic_tmp_consumable',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), nullable=False),
    sa.Column('stock_level', sa.INTEGER(), nullable=True),
    sa.Column('unit', sa.VARCHAR(length=20), nullable=True),
    sa.Column('reorder_level', sa.INTEGER(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('usage_description', sa.TEXT(), nullable=True),
    sa.Column('min_stock', sa.INTEGER(), nullable=True),
    sa.Column('max_stock', sa.INTEGER(), nullable=True),
    sa.Column('storage_location', sa.VARCHAR(length=100), nullable=True),
    sa.Column('manufacturer', sa.VARCHAR(length=100), nullable=True),
    sa.Column('supplier', sa.VARCHAR(length=100), nullable=True),
    sa.Column('article_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('ean', sa.VARCHAR(length=13), nullable=True),
    sa.Column('unit_price', sa.FLOAT(), nullable=True),
    sa.Column('currency', sa.VARCHAR(length=10), nullable=True),
    sa.Column('last_ordered_date', sa.DATE(), nullable=True),
    sa.Column('last_order_quantity', sa.INTEGER(), nullable=True),
    sa.Column('has_expiry', sa.BOOLEAN(), nullable=False),
    sa.Column('expiry_date', sa.DATE(), nullable=True),
    sa.Column('image_filename', sa.VARCHAR(length=255), nullable=True),
    sa.Column('datasheet_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('hazard_symbols', sqlite.JSON(), nullable=True),
    sa.Column('safety_warnings', sqlite.JSON(), nullable=True),
    sa.Column('specifications', sqlite.JSON(), nullable=True),
    sa.Column('compatibility_tags', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_consumable')
    )
    # ### end Alembic commands ###
