"""add_spool_weight_and_reorder_level_to_filament_type

Revision ID: e2e3dead7215
Revises: 48c6ed6ca4a5
Create Date: 2025-09-14 18:54:05.261653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2e3dead7215'
down_revision = '48c6ed6ca4a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filament_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spool_weight_g', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reorder_level_g', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filament_type', schema=None) as batch_op:
        batch_op.drop_column('reorder_level_g')
        batch_op.drop_column('spool_weight_g')

    # ### end Alembic commands ###
